version: '3.8'
services:
  db:
    image: postgres:16
    container_name: taskjobber-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskjobber
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
